name = "hammers"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.34.1"

[[require]]
name = "Duper"
git = "https://github.com/leanprover-community/duper.git"
rev = "v4.34.1"

[[require]]
name = "Canonical"
git = "https://github.com/chasenorman/CanonicalLean.git"
rev = "v4.34.0"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Seeded"

[[lean_lib]]
name = "Bench"
globs = ["Bench.+"]
